version: '3.9'
services:
  react-app:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    volumes:
      - ./frontend:/src
    command: sh -c 'cd app && PORT=8080 yarn start'
    ports:
      - '8080:8080'
    stdin_open: true
