version: '3.9'
services:
  api:
    build:
      context: ./server
      dockerfile: dockerfile
    volumes:
      - ./server:/srv:cached
    ports:
      - '8080:8080'
    tty: true
  react-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/src
    command: sh -c "cd app && PORT=80 yarn start"
    ports:
      - "80:80"
    stdin_open: true
