version: '3.9'
services:
  react-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/src
    command: sh -c "cd app && yarn add react-datepicker && yarn add react-router-dom sass && PORT=80 yarn start"
  api:
    build:
      context: ./server
      dockerfile: dockerfile
    volumes:
      - ./server:/srv:cached
    ports:
      - '8080:8080'
    tty: true
  db:
    privileged: true
    build:
      context: ./db
      dockerfile: dockerfile
    container_name: POSTGRESQL
    ports:
      - 5432:5432
    volumes:
      # - ./db/postgres:/var/lib/postgresql/data:Z
      - ./db/script:/docker-entrypoint-initdb.d 
    environment:
      - POSTGRES_USER=testroot
      - POSTGRES_PASSWORD=Password!
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

# volumes:
#   postgres:
#   pgadmin:
